### PR TITLE
Correct bundle name for the edge browser on mac

### PR DESCRIPTION
**Pull request by SCdF**
As of today, on Intel Macs anyway.

### CODE REVIEW

**Comment by knausj85** [comment]
Thanks, though this isn't the ideal way to address this one. I think you should instead a `microsoft_edge` app definition for the Mac in this file:

https://github.com/knausj85/knausj_talon/blob/0ef6e37c11ce748d5e0ed3cf6812434b9c624e2a/apps/edge/edge.py#L6

The `talon copy context pie` command (from talon_helpers.talon) will attempt to generate the correct application definition on a per-platform basis for the focused application to the clipboard, and you can just paste it into that file.

The advantage of defining an app in this way: we can update the app definition in one place in python, and re-use everywhere (.talon files, .py). 

[See firefox for example](https://github.com/knausj85/knausj_talon/blob/0ef6e37c11ce748d5e0ed3cf6812434b9c624e2a/apps/firefox/firefox.py#L14)

**Comment by SCdF** [comment]
Oh cool I didn't know about that, will do and test tmrw

**Comment by SCdF** [comment]
Done, and tested on an Intel Mac. @knausj85 please check it out :-)

**Comment by knausj85** [comment]
Looks good, thanks.

**Pull request merged**
