### PR TITLE
selected_text(): use capture().text() not .get()

### PR DESCRIPTION
**Pull request by rntz**
Squashes some warnings from talon. My only concern here is that this API may not yet be in public talon. Can someone check?

### CODE REVIEW

**Comment by auscompgeek** [comment]
It's not in public Talon.

**Comment by rntz** [comment]
this should be in public talon as of 0.3, although we ought to test that.

**Comment by phillco** [comment]
Did 0.3 release to windows yet?

**Comment by rntz** [comment]
Apparently not :(

**Comment by rntz** [comment]
it did now

**Review by pokey — APPROVED** [review]

**Pull request merged**
