### PR TITLE
#920 Inconsistent function names/descriptions in operators_assignment.py and operators_assignment.talon

### PR DESCRIPTION
**Pull request by chrisnicollo**
#920 
This should make it so that the bitwise assignment operators are now able to be used.

### CODE REVIEW

**Comment by chrisnicollo** [comment]
It looks like the pre-commit program wanted to push some changes to the code, but it couldn't because I didn't allow edits by maintainers. However, I have since fixed that so that it can fix the issues if the checks are run again.

**Review by pokey — APPROVED** [review]
Looks good to me!  Re pre-commit, maybe you didn't check the "Allow edits by maintainers" box?

**Comment by chrisnicollo** [comment]
That's what it seems like to me, and I checked that box to fix it. I'm not sure if you have to run that pre-commit again to fix any errors.
Also, some of the bitwise assignment operators were never given spoken commands as far as I can tell. I could probably just follow talon convention on those to add them in, but I'm don't know whether to put them in the same pull request.

**Review by pokey — APPROVED** [review]
I pushed an empty commit to kick CI; seems to have done the trick

Re adding other spoken forms; go ahead if you think you'll use them!  Prob for follow-up PR tho; let's get this one merged in as it fixes a bug

Thank you!

**Pull request merged**
