### PR TITLE
basic twitter shortcut support

### PR DESCRIPTION
**Pull request by fidgetingbits**
twitter website shortcuts

### CODE REVIEW

**Comment by dwiel** [comment]
it looks useful to me, any reason not to merge this?

**Comment by fidgetingbits** [comment]
I think the main problem is relying on `win.title` with a fuzzy match for twitter, even though it works in practice it's probably prone to false positive. so the option suggested in the github issue #117 is to use a browser extension that exposes the actual in the tab, so I just need to add a common about that (will do shortly)

the other thing I need to do is move it to the new `web` folder

**Comment by fidgetingbits** [comment]
this is updated now, with a markdown file talking about matching using the plugin (not sure the best place to put that, so freedom move)

**Comment by knausj85** [comment]
Thank you!

**Pull request merged**
