### PR TITLE
add phones word/word left/word right commands

### PR DESCRIPTION
**Pull request by rntz**
useful for applying homophones to the word left of/right of/at cursor

### CODE REVIEW

**Comment by knausj85** [comment]
I would suggest adding an optional `<number_small>` to those phones word left/right commands.

**Comment by rntz** [comment]
The idea being to select the nth word in that direction, so eg if you're after "foo bar baz" `phones two words left` would select "bar"? That should be doable...

**Comment by xavier630** [comment]
Not in scope for this PR but we should make a generic selection generator that applies selection before applying a command since it's a pattern that keeps coming in more places and all of the selections are identical (`phones, cut, copy, snake, hammer` etc all have/will eventually have the same selections `left, right, word, line, all, etc` variants that all need to be maintained and are basically identical).

Will raise an issue tomorrow.

**Comment by rntz** [comment]
I have some thoughts on that, but you should check out the text navigation commands in https://github.com/knausj85/knausj_talon/blob/master/text/text_navigation.talon, which may already do some of what you're imagining.

**Comment by rntz** [comment]
ok, I've updated this to allow eg "phones second word left" or "phones third word right". it did involve adding some new actions for moving n words left or right (had to do this instead of using core.repeat() because needed to handle moving 0 words right/left, which is the default).

**Pull request merged**
