### PR TITLE
feat(#945): Reimplement system_command(_nb) actions

### PR DESCRIPTION
**Pull request by splondike**
Addresses the issues with the current implementation mentioned by lunixbochs in #945 and will additionally fix the following:

* system_command now throws an error when the command exits unsuccessfully.
* system_command_nb now leaves the child process running when Talon exits.

I've tested this implementation on Linux, OSX, and Windows against variants of the test cases listed here: https://github.com/knausj85/knausj_talon/issues/945#issuecomment-1464885283 and it works OK.

# Technical notes

shlex.split doesn't do what you want with Windows' backslash based file paths: "C:\\Windows\\Path" gets converted to "C:WindowsPath". The lexer I implemented here lets you escape quotation characters, but backslash plus a non quote character comes out unchanged. This lexer doesn't support inline comments or newlines.

### CODE REVIEW

**Comment by splondike** [comment]
@fidgetingbits FYI, if this gets merged your use of shell constructs will no longer work (e.g. https://github.com/fidgetingbits/knausj_talon/blob/master/apps/i3wm/i3wm.talon#L28).

You could fix that line by wrapping the whole command in a bash shell like this:
```sh
    user.system_command("bash -c \"/home/aa/scripts/i3/i3-nth_window_in_workspace.py $(i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name') {number_small-1}\"")
```

**Comment by fidgetingbits** [comment]
> @fidgetingbits FYI, if this gets merged your use of shell constructs will no longer work (e.g. https://github.com/fidgetingbits/knausj_talon/blob/master/apps/i3wm/i3wm.talon#L28).
> 
> You could fix that line by wrapping the whole command in a bash shell like this:
> 
> ```shell
>     user.system_command("bash -c \"/home/aa/scripts/i3/i3-nth_window_in_workspace.py $(i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name') {number_small-1}\"")
> ```

Thanks for the heads up

**Comment by rntz** [comment]
I haven't looked at this deeply but I would really rather we not have to maintain a custom lexer, is there an alternative?

**Comment by splondike** [comment]
I've put my thoughts on how to proceed in #945 and have marked this as a draft until we work that out.

**Comment by splondike** [comment]
Sounds like we won't be merging this in any time soon. I'm going to close this out in order to stop cluttering the PR list. It's linked in the issue so we can recover the code pretty easily if we want to go this way.

**Pull request closed without merging**
