### PR TITLE
add 'proud' command for inserting capitalized word

### PR DESCRIPTION
**Pull request by jmegner**
I have found this command very useful even though we already have 'title' command.  Just, like how the 'word' command is useful in addition to the 'say' command.

### CODE REVIEW

**Comment by pokey** [comment]
Yeah super useful. I use "proud" fwiw. We may start using "grand" in cursorless so might be marginally better to steer clear of it, all else being equal. See https://github.com/cursorless-dev/cursorless/issues/124

**Comment by jmegner** [comment]
@pokey awesome, thanks, I have made the change from grand to proud.

**Review by knausj85 — DISMISSED** [review]
I believe we'll still want to call
user.add_phrase_to_history(word)
as in the command above for improved undo support

otherwise, looks great

**Comment by rntz** [comment]
It appears that `user.insert_formatted` actually adds the formatted phrase to history already, so I don't think we need that.

**Comment by rntz** [comment]
Arguably, we shouldn't be doing that; it's inconsistent with the request from aegis to avoid an `insert_with_history` command. But that's out of scope for this PR, I think.

**Review by rntz — APPROVED** [review]

**Pull request merged**
