### PR TITLE
Use insert in talonscript instead of insert_with_history

### PR DESCRIPTION
**Pull request by timo**
This makes these commands transparent for the purpose of parsing
talonscript to figure out what it does

### CODE REVIEW

**Comment by timo** [comment]
i decided not to remove the insert_with_history action, because perhaps someone somewhere is using it in their own scripts (nothing in search.talonvoice.com, at least) and we don't seem to have anything that does deprecations

**Comment by rntz** [comment]
Why is add_phrase_to_history() followed by insert() more transparent than insert_with_history()?

**Comment by auscompgeek** [comment]
Slack discussion from here onwards: https://talonvoice.slack.com/archives/C7ENXA7C4/p1659211727193269

**Review by splondike — APPROVED** [review]
Change sounds fine given the Slack context. Having the raw inserts improves the potential for automatically determining how to type a given phrase (according to aegis, sounds quite fancy to me).

**Comment by rntz** [comment]
We should probably deprecate or remove insert_with_history if we want to go this route.

**Comment by splondike** [comment]
Yeah, deprecating it would be a good idea. I dropped a proposal for how we might deprecate actions in here: https://github.com/knausj85/knausj_talon/issues/940 . Does that sound good for this case?

**Comment by splondike** [comment]
I can make the adjustments needed here once we have #1027 merged.

**Review by splondike — APPROVED** [review]

**Pull request merged**
