### PR TITLE
Add guake.talon

### PR DESCRIPTION
**Pull request by khornlund**
Add talon implementation for [guake](http://guake-project.org) terminal

It's been a few months since I've worked on talon scripts so let me know if I've missed some part of best practice

### CODE REVIEW

**Comment by knausj85** [comment]
Shouldn't their be an app definition in https://github.com/knausj85/knausj_talon/blob/master/code/application_matches.py for this?

**Comment by khornlund** [comment]
> Shouldn't there be an app definition in https://github.com/knausj85/knausj_talon/blob/master/code/application_matches.py (or its own .py) for this?

How do they work? Do you need one for each app you match on?

**Comment by knausj85** [comment]
Yeah, that's essentially correct. These are defined in .py now so the same match can be used in several places.

The old approach of matching the executable/bundle/etc is deprecated in .talon directly, and will be removed eventually.

**Comment by dwiel** [comment]
When should applications_matches be used/not be used?

**Comment by knausj85** [comment]
My 2c:
If an application has it's own .py, I think the app def should go there.
If there isn't a need for its own .py, slap it applications_matches.

?

**Comment by dwiel** [comment]
So then it should never go at the top of a .talon file?

**Comment by knausj85** [comment]
Oh, you were asking a different question. My bad.

This snippet: 
```
from talon import Context, Module
mod = Module()
apps = mod.apps
apps.windows_terminal = """
os: windows
and app.name: WindowsTerminal.exe 
"""
```

Defines the application match for window terminal that can be used in both .py and .talon. 

```
app: windows_terminal
-
stupid test: "Do something
```

The approach where talon would magically match against name/exe/bundle via `app: magic.bundle.something` behind the scenes is deprecated and will disappear someday.

**Comment by dwiel** [comment]
Gotcha

**Pull request merged**
