### PR TITLE
Add phones exit button and make all phones options clickable

### PR DESCRIPTION
**Pull request by xavier630**
image

### CODE REVIEW

**Comment by xavier630** [comment]
https://github.com/knausj85/knausj_talon/issues/530

**Comment by splondike** [comment]
This seems good, but I'd probably just label it as 'phones hide' matching the existing voice command. It doesn't look like we have 'exit' used as a way of closing this kind of thing elsewhere in the voice commands (we have 'hide', 'off', 'close' in other places). We do have it for shutting down a program, but only one instance I think. It'd be good to keep the number of 'close' type verbs down, and preferably reduce them!.

**Comment by xavier630** [comment]
Sounds reasonable, will update it to hide 👍

**Comment by splondike** [comment]
Nice one :).

**Pull request merged**
