### PR TITLE
add support for protonmail web application

### PR DESCRIPTION
**Pull request by fidgetingbits**
i originally had this in its own web/ directory on my fork rather than apps since its technically a website and so the short cuts should roughly match for every system, but i guess the problem is that on mac the control keys will end up being command key. but i think for stuff like this it would be better to have some sort of setting where we say on mac use command key and on everything else use control key and then just have talon figure it out on the fly?

### CODE REVIEW

**Comment by knausj85** [comment]
I think a /web directory makes sense, i can see a need for both e.g. /linux/web and just /web/, depending on how things are implemented for a given app. 

Just for reference, there a few ways to handle cmd vs ctrl
- defining actions in python. the platform can be detected, and the appropriate shortcut used. 
- just declaring actions in python, and defining per-OS web app actions in a .talon file. the command file can be defined in a separate .talon file. This is what i've done for e.g. the edit commands
- just separate .talon files for each OS

Few minor notes:
- Until someone vets these on Windows or Mac, I'd vote to add 
  os: linux 
- i do wonder if the win.title is specific enough? Should it be some regex of mail.protonmail.com ?

**Comment by fidgetingbits** [comment]
unfortunately win.title doesn't include the url (nor do any other window attributes on linux afaict). Instead you get something like this which comes from the tab name (this output is from running `xprop`):

```
WM_ICON_NAME(STRING) = "Inbox | blah@blah.com | ProtonMail - Mozilla Firefox"
```

**Comment by fidgetingbits** [comment]
I tested it with tags and it works fine, and I also added the linux os bit.

**Comment by knausj85** [comment]
Thanks!

**Pull request merged**
