### PR TITLE
changed "go marks" for consistency with sidebar commands

### PR DESCRIPTION
**Pull request by maxbruening**
"bar marks" is consistent with other sidebar commands

### CODE REVIEW

**Comment by splondike** [comment]
This does look like a consistency improvement. In order to help people migrate to the new command, would you be able to follow the steps in the [deprecation process](https://github.com/knausj85/knausj_talon/blob/main/core/deprecations.py) (see doc block at the top of that file)? So there should be an entry in BREAKING_CHANGES.txt and the old command should continue to work (with a notification).

**Comment by splondike** [comment]
@maxbruening Would you still like to get this merged in?

**Comment by maxbruening** [comment]
I hope this worked.  The new commits are in my branch  but I'm not sure how to add them to the pull request.

**Comment by splondike** [comment]
I'm not sure the changes made it through to your Github fork. I'd be looking for:

* An entry in this file: https://github.com/maxbruening/knausj_talon/blob/max-vscode/BREAKING_CHANGES.txt
* For the old command to continue to exist and work in vscode.talon, but to have an additional line like `        user.deprecate_command("2023-06-03", "go marks", "bar marks")`

**Comment by splondike** [comment]
In terms of updating the PR, if you update the branch in your repo that should update the PR here.

**Comment by maxbruening** [comment]
I hope this did it. Third time is a charm.

**Review by knausj85 — APPROVED** [review]

**Pull request merged**
