### PR TITLE
Break up code.py into one file per tag

### PR DESCRIPTION
**Pull request by wenkokke**
Implements the changes proposed in the first step of #651.

This pull request should not contain any breaking changes.

### CODE REVIEW

**Review by splondike — COMMENTED** [review]
lang/snippets.talon -> code/snippets.talon should probably move to something like apps/generic_snippets.talon . It's more an editor/IDE thing than a language thing I think.

I believe the intention with the code/ folder was to just have Python in there (at least that's how it currently works).

Aside from that, this change looks good to me. It's nicer to have things broken up like this.

**Comment by fidgetingbits** [comment]
agreed about snippets changing to generic_snippets.talon. also agree otherwise it looks much better this way

**Comment by wenkokke** [comment]
I've migrated the code for snippets into the apps folder, under `generic_snippets`.

**Review by splondike — APPROVED** [review]
LGTM, will wait for a second approval to merge.

**Review by knausj85 — APPROVED** [review]

**Comment by knausj85** [comment]
Looks good, thanks

**Pull request merged**
