### PR TITLE
Remove unused formatter implementations

### PR DESCRIPTION
**Pull request by xavier630**
Removes a couple of old formatter implementations which no commands map to any longer.

### CODE REVIEW

**Review by rntz — APPROVED** [review]
I think these are here for backward-compatibility reasons, for people who've been using knausj for a while. I'm okay with removing them but @knausj85 might want to keep them? If we want to keep them maybe we should add a comment so that we don't get more PRs about removing them.

**Comment by xavier630** [comment]
Going by @splondike's comment here, they may be okay to remove https://github.com/knausj85/knausj_talon/pull/693#issuecomment-992011936

**Comment by knausj85** [comment]
There's a few people here and there using these, so I'm slightly hesitant:
https://search.talonvoice.com/search/?q=formatters_dict%5B%22FIRST_THREE%22%5D&fold_case=auto&regex=false&context=true

I don't know where to draw the line on these sorts of things

**Comment by xavier630** [comment]
Happy to defer to you guys as maintainers. Given that it was already commented out, it feels a bit like dead code to me.

**Comment by xavier630** [comment]
But agreed that we don't want to break functionality of forks when they pull develop, so happy for you to close

**Pull request merged**
