### PR TITLE
work around for pop to stop scroll with zoom mouse

### PR DESCRIPTION
**Pull request by okonomichiyaki**
this will allow you to stop the continuous scroll
using pop without activating zoom mouse

### CODE REVIEW

**Comment by knausj85** [comment]
I don't think this will work if the zoom mouse is toggled via the Talon context menu? I'll poke at it later.

**Comment by knausj85** [comment]
Well, here's a potential "fix" hehe. I'm not sure this is wise to include in the community repository though.

**Comment by okonomichiyaki** [comment]
yeah that makes sense, feel free to close this pull request for now. to be honest this was really more of an issue playing games where I was using the scroll mode to zoom in and out, i'm content to have the work around for myself for that one narrow case

**Comment by splondike** [comment]
Closing pull request at okonmichiyaki's suggestion (and lack of activity for 8 months).

**Pull request closed without merging**
