### PR TITLE
github shortcut support

### PR DESCRIPTION
**Pull request by fidgetingbits**
this is stuff I added for github. unfortunately they don't include the actual name github in their title, so currently the window matching has to be tweaked for whatever repo you are using or just enable it across the board. in light of that I just said it as github for now so people can change it if they want. I did contact github and  asked them to change it on their website, but I haven't heard anything back

### CODE REVIEW

**Comment by knausj85** [comment]
maybe try something like https://addons.mozilla.org/en-US/firefox/addon/domain-in-title/ ?

**Comment by fidgetingbits** [comment]
I tried out that out and it works perfectly so I guess in the meantime I'll just to add that url to the title match and add a  comment that  people will need to use it

**Comment by knausj85** [comment]
Thanks for giving it a whirl. I think this is a sensible approach for web app stuff - m ost browsers have some sort of plugin for adding the domain to the title

**Comment by knausj85** [comment]
FYI I re-arranged the app folder as discussed for https://github.com/knausj85/knausj_talon/issues/129, and added a 'web' subfolder. Just a note to perhaps move it when we circle back to this one.

e.g.,
https://github.com/knausj85/knausj_talon/blob/master/apps/web/outlook.talon

**Comment by fidgetingbits** [comment]
cool will do

**Comment by fidgetingbits** [comment]
has been moved to web now and using the URL

**Comment by knausj85** [comment]
Thank you!

**Pull request merged**
