### PR TITLE
#598 Gaze scrolling relative to the cursor posiiton

### PR DESCRIPTION
**Pull request by daanvdh**
#598

### CODE REVIEW

**Comment by rntz** [comment]
@knausj85 hey, can this be merged / should it be worked on / should we close it? I don't use an eye tracker so it's a bit opaque to me. I'm trying to give old PRs some attention so they don't get forgotten.

**Comment by splondike** [comment]
It's been more than a year since this was put up and we asked for help reviewing it (since I don't think we have a regular maintainer that uses an eye tracker).

Given that, I don't think we have the capacity to test this. As such I think I'd be in favour of closing it to reduce the length of the stagnant PR list. It's unfortunate since it sounds useful and has obviously had a bit of work put in. We can leave the issue open (which will reference the code in this PR), so if somebody wishes to pick it up and find some testers in the future they can dust off the existing code.

**Comment by deepbluezen** [comment]
Potential user review at request of splondike from slack. Tested on beta v0.3.1-57-g0dd4 (57), Win10. I use control mouse routinely.
I can see the use case it's solving for someone who uses zoom mouse and it worked effectively for me across a number of programs that I use which are multipaned such as blender or unity. For me I wouldn't use it as it would have to much friction dropping out of the control mouse mode and I don't have an issue just clicking on drag bars or using the wheel up/down commands.
I don't have a feel for how much of the community are using one eyetracking mode over the other? Even if it wouldn't be of use to me I would be happy to support testing if it was taken forwards.

**Comment by splondike** [comment]
Given deepbluezen wouldn't use this themselves and it would take a bit of effort for us to coordinate re-implementing and testing this on the current knausj main I think I'll close this out.

As stated in my last comment if somebody wants to push this forward we've still got the original issue and the code isn't lost, just closed.

**Pull request closed without merging**
