### PR TITLE
Provide setting to unconditionally enable pop-to-click.

### PR DESCRIPTION
**Pull request by codecat555**
Per aegis - https://talonvoice.slack.com/archives/C9LFDNBAQ/p1652291642060249

### CODE REVIEW

**Comment by pokey** [comment]
Is it fair to say that this one partially solves #755?  Is it worth folding the rest of #755 into this PR?

**Comment by codecat555** [comment]
Sorry, I'm not up to addressing all of #755 at this time. I didn't even realize that issue existed before now.

I just jumped on this opportunistically to help reduce the support burden for aegis and to streamline the slack discussions around this point. Oh, and to make things easier for people too.

**Comment by pokey** [comment]
Thanks for being upfront about that; obviously work / health has to take priority

My concern with merging this PR is that we may be introducing a setting that we'll need to support going forward, when we plan to change it soon

I don't use pop to click or an eye tracker, so I don't have a particularly strong opinion, but I do think it's worth aligning on #755 before merging this one

WDYT @knausj85 @rntz

**Comment by codecat555** [comment]
Well, you could accept this incremental improvement if you were able to decide which settings names you want before completing the full implementation. Whatever you guys want to do with this is fine with me.

**Comment by pokey** [comment]
That seems reasonable. Let's see where discussion goes on #755

**Comment by splondike** [comment]
It looks like we have a consensus in #755 around adding a new setting that just enables pop to click more or less unconditionally. As such I think the next step is to convert this PR into an implementation of the design described there.

**Review by splondike — CHANGES_REQUESTED** [review]
Marking as 'changes requested'; we should implement the decision in #755. Either in this PR, or by closing this out and making a new one.

**Comment by splondike** [comment]
Replaced this with #1139 , closing.

**Pull request closed without merging**
