### PR TITLE
Handle capitalization of e.g. and i.e. within prose.

### PR DESCRIPTION
**Pull request by wolfmanstout**
This works out of the box in Dragon. To test in Conformer you'll need to add something like this to additional_words.csv:
```
i.e.,I E
e.g.,E G
```

### CODE REVIEW

**Comment by wolfmanstout** [comment]
I'll add a test and fix for newline after period as well.

**Comment by rntz** [comment]
I haven't looked at this in detail, but it doesn't look like it defines any new states accepted by `auto_capitalize`, which means it's violating one of the intended laws about `auto_capitalize` (which I really should have documented), namely that the following should be true:

```
(result, state2) = auto_capitalize(text1 + text2, state)
```
should behave the same as:
```
(result1, state1) = auto_capitalize(text1, state)
(result2, state2) = auto_capitalize(text2, state1)
result = result1 + result2
```


The goal is to make sure that no matter how the text that gets inserted is "chunked" we produce the same result. The approach I used is to make auto_capitalize should be a resumable finite state machine. Unfortunately this is probably hard to do by hand if you want it to recognize long strings like "e.g." and "i.e." (you'll get a large number of states). Maybe we should give up on this approach and just accept that we'll produce bad results in some unusual cases.

**Comment by wolfmanstout** [comment]
Yes this violates that in several ways, actually. One way to avoid a bunch of state bools but meet that spec is to simply use the formatted output as the state. In order to avoid performance problems a couple more reasonable constraints might be: state size is O(1) and multiple successive calls takes time O(n) regardless of chunking. This could probably be achievable by tracking a list of strings to match and only keeping the max length of that as the state. 

Another option is to formally document the expectations this has on chunking. I agree that it feels brittle now without that.

**Comment by rntz** [comment]
I don't have time to try to figure out the Right Way to do this right now, and it seems like this PR's approach would be better than nothing for most users. If you add a comment explaining under what circumstances this will break I'd be happy to merge this; I'll file an issue about fixing it in the long-term.

**Comment by wolfmanstout** [comment]
Thanks, done.

**Pull request merged**
