### PR TITLE
Abbreviate

### PR DESCRIPTION
**Pull request by fidgetingbits**
more abbreviations i've he started using. as often as the case some might be a bit questionable: ex hypertext -> http, web -> www, etc

### CODE REVIEW

**Comment by dwiel** [comment]
LGTM after merge conflicts fixed

**Comment by fidgetingbits** [comment]
I don't get a merge conflict warning?

**Comment by dwiel** [comment]
Ah you are right. Merge is ok. Rebase is not. Haven't looked into why

**Comment by fidgetingbits** [comment]
I have never used rebase on github so I'm not sure what kind of a problem it would have. should probably read more into rebasing in general..

**Pull request merged**
