### PR TITLE
Add a question formatter to Talon

### PR DESCRIPTION
**Pull request by xavier630**
Adds a question formatter `ask` to Talon.

Example:
`"Ask where do I go"` -> `"where do I go?"`

In the future, I'd like to make an `ask` formatter which auto-capitalises the first word. For now I'm keeping it quite simple and assumption-free.

### CODE REVIEW

**Comment by splondike** [comment]
For me I probably wouldn't use this formatter, I'd just say "sentence where do I go <pause> question". <pause> would be half a second or so. By the same token I don't use the existing string or dubstring formatters either (I use "quote say blah blah <pause> quote"). Do you think it would add much benefit over the current approach (i.e. the one I use)?

Will leave this open thought to let others add their views.

In general I feel like there are benefits to limiting the addition of global commands to the repo if they're not likely to be used too widely. Specifically it reduces the length of automatic help windows, the sise of the more heavily viewed parts of the codebase, the maintenance burden (we have no way of knowing what commands people use once they're released, so we basically have to keep all of them), and the chance of misrecognitions. Those are the reasons I ask for justification on some of these PRs, I appreciate the effort to improve things though :).

**Comment by xavier630** [comment]
Happy to let others jump in. If no one finds it useful, I can always keep this on my fork only 👍

**Comment by rntz** [comment]
You should also be able to say "sentence what time is it question mark"

**Comment by pokey** [comment]
After some discussion I think we decided that we should let users implement the sort of thing on their own branch

**Pull request closed without merging**
